name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11.6
          cache: "pip"
      - name: "installation"
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt
          pip install wheel setuptools flash-attn==2.5.8 --no-build-isolation
      - name: "black"
        run: black . --check --diff --color
      - name: "isort"
        run: isort . --check --diff
      - name: "mypy"
        run: mypy
      - name: "pytests"
        run: pytest
